version: '3.8'

services:
  postgres:
    container_name: card-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: card-app
    volumes:
      - ./data/pg:/var/lib/postgresql/data

  card_app:
    build: ./
    container_name: card_app
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app/src
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION_URL: postgresql://docker:docker@postgres:5432/card-app?schema=public
    depends_on:
    - postgres
